name: test_do_an
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17  # Phiên bản mới nhất của flutter_svg
  sqflite: ^2.3.0          # Để sử dụng SQLite
  path_provider: ^2.1.1   # Để lấy đường dẫn lưu trữ
  path: ^1.8.3           # Để xử lý đường dẫn
  shared_preferences: ^2.2.2  # Để lưu trạng thái đăng nhập
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/