name: test_do_an
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17  # Phiên bản mới nhất của flutter_svg
  sqflite: ^2.3.0          # Để sử dụng SQLite
  path_provider: ^2.1.1   # Để lấy đường dẫn lưu trữ
  path: ^1.8.3           # Để xử lý đường dẫn
  shared_preferences: ^2.2.3  # Để lưu trạng thái đăng nhập
  image_picker: ^1.0.7
  just_audio: ^0.9.36 # Thêm gói này để phát nhạc
  palette_generator: ^0.3.3+3 # Thêm gói này để trích xuất màu từ hình ảnh
  mailer: ^6.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/songs/
    - assets/artist_avatars/
    - assets/song_avatars/
    - assets/album_avatars/
    - assets/database/music_app.db